image: archlinux
shell: true
packages:
  - base-devel
sources:
  - https://git.sr.ht/~petrus/lowx
tasks:
  - setup-env: |
      echo 'export PATH=~/.local/bin:$PATH' >> .buildenv
      mkdir -p .local/bin
  - build: |
      cd src
      make lox
  - install: |
      cd src
      make install
  - test: |
      lowx -v
      lowx doc/examples/ultimate.lx
artifacts:
  - .local/bin/lowx
